name: TNTPlugin
author: Julian, Johannes
main: antitnt.Main
description: TNT Plugin
version: 1.1.0
commands:
    TNT:
        permission: antitnt.admin
        usage: "Usage /TNT [true,false]"

permissions:
    antitnt.admin:
        default: op