name: TNTPlugin
author: Julian, Johannes
main: antitnt.Main
description: TNT Plugin
version: 2.0.0
commands:
    TNT:
        permission: antitnt.admin
        usage: |
            "Usage: /<command> [true,false]"
            "Usage: /<command> ignite [true,false]"
        description: Prevents TNT from explosion

permissions:
    antitnt.admin:
      default: op