name: TNTPlugin
author: Julian, Johannes
main: antitnt.Main
description: TNT Plugin
version: 2.0.0
commands:
  antiTNT:
    permission: antitnt.admin
    usage: |
      "Usage: /<command> [enable,disable]"
      "Usage: /<command> ignite [true,false]"
    description: Prevents TNT from explosion

permissions:
  antitnt.admin:
    default: op